global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'milvus'
    static_configs:
      - targets: ['milvus:9091']

  - job_name: 'flask-app'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Flask metrics endpoint